version: "3.9"

services:
  api:
    build:
      context: .
      target: dev
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres

  # api-test:
  #   build:
  #     context: .
  #     target: test
  #   volumes:
  #     - ./:/app

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: labuonapasta
      POSTGRES_USER: postgres
